version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: eventpulse_postgres
    restart: always
    environment:
      POSTGRES_USER: eventpulse
      POSTGRES_PASSWORD: eventpulse
      POSTGRES_DB: eventpulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
